/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3f29e474-6e5e-4e1b-8ae2-bd7753fa61d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RMVpHveen",
    "aws_user_pools_web_client_id": "1algrt0533k1ujtuou4r6jdmjk",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api888b1d53",
            "endpoint": "https://ud037dzvxf.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "amplifyreactapp-20210412165441-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1x6wnpb0vf9d4.cloudfront.net"
};


export default awsmobile;
